---

stages:
    - nag
    - test
    - publish

container:
    image: registry.gitlab.com/modioab/base-image/fedora-29/build:master
    stage: publish
    only:
        - master
        - tags
    script:
        - make -f build.mk login
        - make build-publish

check:
    image: registry.gitlab.com/modioab/base-image/fedora-29/build:master
    stage: test
    when: always
    before_script:
        - pip3 install --upgrade --upgrade-strategy eager flake8 black
    script:
        - make check

test:
    image: registry.gitlab.com/modioab/base-image/fedora-29/python:master
    stage: test
    when: always
    before_script:
        - pip3 install -r requirements_dev.txt
        - pip3 install .
    script:
        - python3 setup.py test
        - nagger nag

nagger:
    image: registry.gitlab.com/modioab/nagger:master
    stage: nag
    script:
        - nagger nag
