# vim: expandtab:ts=8:sw=2:tw=80:fdm=marker:ft=yaml:
%YAML 1.1
---
include:
  # Only run for branches and tags
  # https://docs.gitlab.com/ee/ci/yaml/#workflowrules-templates
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - project: ModioAB/CI
    ref: main
    file:
      - /ci/default.yml
      - /ci/container.yml


container:build:
  extends: .container:build

# Run "nagger nag" from our freshly built container
nagger:ci:
  image: registry.gitlab.com/modioab/nagger:${CI_PIPELINE_ID}
  stage: test
  script:
    - nagger nag

check:
  stage: test
  needs: []
  before_script:
    - pip3 install --upgrade --upgrade-strategy eager flake8 black
  script:
    - make check

test:
  stage: test
  needs: []
  before_script:
    - pip3 install -r requirements_dev.txt
    - pip3 install .
  script:
    - pytest


container:publish:
  extends: .container:publish
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        IMAGE_TAG_SUFFIX: latest
    - !reference [.container:publish, rules]
...
